const popularData = [
    {
        "adult": false,
        "backdrop_path": "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        "genre_ids": [28, 35, 878],
        "id": 533535,
        "original_language": "en",
        "original_title": "Deadpool & Wolverine",
        "overview": "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        "popularity": 2095.943,
        "poster_path": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        "release_date": "2024-07-24",
        "title": "Deadpool & Wolverine",
        "video": false,
        "vote_average": 7.7,
        "vote_count": 2972
    },
    {
        "adult": false,
        "backdrop_path": "/Asg2UUwipAdE87MxtJy7SQo08XI.jpg",
        "genre_ids": [28, 14, 27],
        "id": 957452,
        "original_language": "en",
        "original_title": "The Crow",
        "overview": "Soulmates Eric and Shelly are brutally murdered when the demons of her dark past catch up with them. Given the chance to save his true love by sacrificing himself, Eric sets out to seek merciless revenge on their killers.",
        "popularity": 2074.307,
        "poster_path": "/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg",
        "release_date": "2024-08-21",
        "title": "The Crow",
        "video": false,
        "vote_average": 5.358,
        "vote_count": 250
    },
    {
        "adult": false,
        "backdrop_path": "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
        "genre_ids": [28, 878, 35, 12, 53],
        "id": 365177,
        "original_language": "en",
        "original_title": "Borderlands",
        "overview": "Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.",
        "popularity": 1333.958,
        "poster_path": "/865DntZzOdX6rLMd405R0nFkLmL.jpg",
        "release_date": "2024-08-07",
        "title": "Borderlands",
        "video": false,
        "vote_average": 5.861,
        "vote_count": 535
    },
    {
        "adult": false,
        "backdrop_path": "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
        "genre_ids": [16, 10751, 12, 35, 14],
        "id": 1022789,
        "original_language": "en",
        "original_title": "Inside Out 2",
        "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        "popularity": 1324.246,
        "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        "release_date": "2024-06-11",
        "title": "Inside Out 2",
        "video": false,
        "vote_average": 7.665,
        "vote_count": 3634
    },
    {
        "adult": false,
        "backdrop_path": "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
        "genre_ids": [16, 10751, 35, 28],
        "id": 519182,
        "original_language": "en",
        "original_title": "Despicable Me 4",
        "overview": "Gru and Lucy welcome a new member to the family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
        "popularity": 1173.836,
        "poster_path": "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
        "release_date": "2024-06-20",
        "title": "Despicable Me 4",
        "video": false,
        "vote_average": 7.17,
        "vote_count": 1640
    },
    {
        "adult": false,
        "backdrop_path": "/cgKZtNSETjXJPkAQ4rasV7dnyQH.jpg",
        "genre_ids": [35, 27, 14],
        "id": 917496,
        "original_language": "en",
        "original_title": "Beetlejuice Beetlejuice",
        "overview": "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
        "popularity": 1024.494,
        "poster_path": "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
        "release_date": "2024-09-04",
        "title": "Beetlejuice Beetlejuice",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 596
    },
    {
        "adult": false,
        "backdrop_path": "/cyKH7pDFlxIXluqRyNoHHEpxSDX.jpg",
        "genre_ids": [80, 28, 53],
        "id": 646097,
        "original_language": "en",
        "original_title": "Rebel Ridge",
        "overview": "A former Marine confronts corruption in a small town when local law enforcement unjustly seizes the bag of cash he needs to post his cousin's bail.",
        "popularity": 934.16,
        "poster_path": "/xEt2GSz9z5rSVpIHMiGdtf0czyf.jpg",
        "release_date": "2024-08-27",
        "title": "Rebel Ridge",
        "video": false,
        "vote_average": 7.04,
        "vote_count": 595
    },
    {
        "adult": false,
        "backdrop_path": "/rwakNepsh0dXVcTtWKUVbDsSYYZ.jpg",
        "genre_ids": [28, 80, 53, 35],
        "id": 573435,
        "original_language": "en",
        "original_title": "Bad Boys: Ride or Die",
        "overview": "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
        "popularity": 926.376,
        "poster_path": "/oGythE98MYleE6mZlGs5oBGkux1.jpg",
        "release_date": "2024-06-05",
        "title": "Bad Boys: Ride or Die",
        "video": false,
        "vote_average": 7.557,
        "vote_count": 1965
    },
    {
        "adult": false,
        "backdrop_path": "/pysPTtYmTcQBlShcxXZwfs3Zp8H.jpg",
        "genre_ids": [878, 53, 27],
        "id": 1064028,
        "original_language": "en",
        "original_title": "Subservience",
        "overview": "With his wife out sick, a struggling father brings home a lifelike AI, only to have his self-aware new help want everything her new family has to offer... Like the affection of her owner and she'll kill to get it.",
        "popularity": 632.132,
        "poster_path": "/gBenxR01Uy0Ev9RTIw6dVBPoyQU.jpg",
        "release_date": "2024-08-15",
        "title": "Subservience",
        "video": false,
        "vote_average": 6.044,
        "vote_count": 57
    }
   
];
export default popularData